name: Continuous Integration

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  lib:
    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idruns-on
    runs-on: [ubuntu-latest]
    strategy:
      matrix:
        # https://github.com/nodejs/release#release-schedule
        node: [ 16, 18, 20 ]

    steps:
      # https://github.com/actions/checkout
      - uses: actions/checkout@v3

      # https://github.com/streetsidesoftware/cspell-action
      - uses: streetsidesoftware/cspell-action@v2
        with:
          incremental_files_only: false

      # https://github.com/actions/setup-node
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: 'npm'

      - run: npm ci

      - run: npm run lint

      - run: npm test

  v30-petsotre-ts:
    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idruns-on
    runs-on: [ubuntu-latest]
    strategy:
      matrix:
        # https://github.com/nodejs/release#release-schedule
        node: [ 16, 18, 20 ]

    steps:
      # https://github.com/actions/checkout
      - uses: actions/checkout@v3

      # https://github.com/actions/setup-node
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: 'npm'
          cache-dependency-path: 'examples/v3.0/petstore-ts/package-lock.json'

      - run: npm ci
        working-directory: examples/v3.0/petstore-ts

      - run: npm run lint
        working-directory: examples/v3.0/petstore-ts

      - run: npm run build:ts
        working-directory: examples/v3.0/petstore-ts

      - run: npm test
        working-directory: examples/v3.0/petstore-ts
